services:
  redis:
    image: redislabs/redismod
    ports:
      - '6379:6379'
  web:
    build: .
    stop_signal: SIGINT
    ports:
      - '8090:8000'
    volumes:
      - .:/code
    depends_on:
      - redis
